name : Build on push
on : 
  push : 
    branches : 
      - feature/*
      - main
      - develop

jobs :
    install:
        uses : ./install.yml
    
    quality-check:
        uses: ./quality-code.yml
    
    chromatic-publish:
        uses: ./chromatic-publish.yml
    
    build:
        runs-on: ubuntu-latest
        needs: [install, quality-check, chromatic-publish]
        steps:
            -   name: Build
                run: npm run build
                    echo "Build completed"
