name : On push to feature branch
on : 
  push : 
    branches : 
      -   feature/*
jobs:
    build:
        runs-on: ubuntu-latest
      
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
      
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
      
            - name: Install dependencies
              run: npm install
            
            - name: Run tests
              run: npm test
            
            - name: Publish to Chromatic
              uses: chromaui/action@latest
              with:
                projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN}}
            
            - name: Add Chromatic review link to pull request
              if: always()
              run: |
                echo "GITHUB TOKEN: ${{ secrets.GITHUB_TOKEN }}"
                exit 1
              # uses: unsplash/comment-on-pr@v1.3.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # with:
              #   msg: |
              #     Chromatic review has been published. [View Chromatic review](https://www.chromatic.com/builds/${{ steps.chromatic-publish.outputs.buildId }})           
            - name: Run lint
              run: npm run lint
      
            - name: Run build
              run: npm run build
                echo "Build completed"