name : On push to feature branch
on : 
  push : 
    branches : 
      -   feature/*
permissions:
  issues: write
  contents: read
  statuses: read
  pull-requests: write
jobs:
    build:
        runs-on: ubuntu-latest
      
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
      
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
      
            - name: Install dependencies
              run: npm install
            
            - name: Run tests
              run: npm test
            
            - name: Publish to Chromatic
              id: chromatic
              uses: chromaui/action@latest
              with:
                projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN}}


            - name: Publish Summary
              run: echo -e "## Chromatic Summary\n\n| Results |\n| --- | --- |\n| Build Results | [Link to chromatic build](${{ steps.chromatic.outputs.url }}) |\n| Storybook Preview | [${{ steps.chromatic.outputs.storybookUrl }}](${{ steps.chromatic.outputs.storybookUrl }}) |\n| Component Count | ${{ steps.chromatic.outputs.componentCount }} |\n| Component Changes | ${{ steps.chromatic.outputs.changeCount }} |\n| Failed test | ${{ steps.chromatic.outputs.errorCount }} /${{ steps.chromatic.outputs.testCount }} |" >> $GITHUB_STEP_SUMMARY

            - name: Add Chromatic review link to pull request
              if: always()
              uses: unsplash/comment-on-pr@v1.3.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                # Chromatic build results are available [here](${{ steps.chromatic.outputs.url }}).
                # Storybook preview is available [here](${{ steps.chromatic.outputs.storybookUrl }}).
                # Component count: ${{ steps.chromatic.outputs.componentCount }}
                # Component changes: ${{ steps.chromatic.outputs.changeCount }}
                # Failed tests: ${{ steps.chromatic.outputs.errorCount }} / ${{ steps.chromatic.outputs.testCount }}.
                msg: |
                  ${{ steps.GITHUB_STEP_SUMMARY}}
                

                
                  
            - name: Run lint
              run: npm run lint
      
            - name: Run build
              run: npm run build
                echo "Build completed"